/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ADLRecord {
  'id' : bigint,
  'staffNotes' : string,
  'assistanceLevel' : string,
  'date' : string,
  'timestamp' : bigint,
  'activity' : string,
}
export type CodeStatus = { 'dnr' : null } |
  { 'fullCode' : null };
export interface CodeStatusChangeRecord {
  'id' : bigint,
  'residentId' : ResidentId,
  'changedByName' : string,
  'changedBy' : Principal,
  'notes' : string,
  'timestamp' : bigint,
  'newStatus' : CodeStatus,
  'previousStatus' : CodeStatus,
}
export interface DailyVitals {
  'id' : bigint,
  'temperatureUnit' : string,
  'bloodGlucose' : [] | [bigint],
  'respiratoryRate' : bigint,
  'temperature' : number,
  'pulseRate' : bigint,
  'oxygenSaturation' : bigint,
  'notes' : string,
  'timestamp' : bigint,
  'measurementDate' : string,
  'bloodPressureDiastolic' : bigint,
  'measurementTime' : string,
  'bloodPressureSystolic' : bigint,
}
export type HealthStatus = { 'ok' : string } |
  { 'error' : string } |
  { 'maintenance' : string };
export interface InsuranceInfo {
  'groupNumber' : string,
  'provider' : string,
  'medicaidNumber' : [] | [string],
  'policyNumber' : string,
  'medicareNumber' : [] | [string],
}
export interface MARRecord {
  'id' : bigint,
  'medicationId' : bigint,
  'notes' : string,
  'timestamp' : bigint,
  'administrationTime' : string,
  'administeredBy' : string,
}
export interface Medication {
  'id' : bigint,
  'dosage' : string,
  'prescribingPhysicianId' : [] | [bigint],
  'name' : string,
  'administrationRoute' : string,
  'isActive' : boolean,
  'administrationTimes' : Array<string>,
  'notes' : string,
  'dosageQuantity' : string,
}
export interface PharmacyInfo {
  'fax' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface Physician {
  'id' : bigint,
  'contactInfo' : string,
  'name' : string,
  'specialty' : string,
}
export interface Resident {
  'id' : ResidentId,
  'bed' : string,
  'dob' : string,
  'status' : ResidentStatus,
  'insuranceInfo' : [] | [InsuranceInfo],
  'admissionDate' : string,
  'marRecords' : Array<MARRecord>,
  'adlRecords' : Array<ADLRecord>,
  'roomNumber' : string,
  'pharmacyInfo' : [] | [PharmacyInfo],
  'medications' : Array<Medication>,
  'dailyVitals' : Array<DailyVitals>,
  'responsibleContacts' : Array<ResponsibleContact>,
  'medicaidNumber' : [] | [string],
  'physicians' : Array<Physician>,
  'codeStatus' : CodeStatus,
  'lastName' : string,
  'roomType' : string,
  'medicareNumber' : [] | [string],
  'firstName' : string,
}
export type ResidentId = bigint;
export type ResidentStatus = { 'active' : null } |
  { 'discharged' : null };
export interface ResponsibleContact {
  'id' : bigint,
  'relationship' : string,
  'name' : string,
  'email' : string,
  'isPrimary' : boolean,
  'phone' : string,
}
export interface UserProfile {
  'userType' : UserType,
  'name' : string,
  'relatedResidentIds' : Array<bigint>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserType = { 'familyMember' : null } |
  { 'staff' : null } |
  { 'resident' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addADLRecord' : ActorMethod<
    [ResidentId, string, string, string, string],
    bigint
  >,
  'addDailyVitals' : ActorMethod<
    [
      ResidentId,
      number,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      [] | [bigint],
      string,
      string,
      string,
    ],
    bigint
  >,
  'addMARRecord' : ActorMethod<
    [ResidentId, bigint, string, string, string],
    bigint
  >,
  'addMedicationToResident' : ActorMethod<[ResidentId, Medication], bigint>,
  'addPhysicianToResident' : ActorMethod<
    [ResidentId, string, string, string],
    bigint
  >,
  'addResident' : ActorMethod<[Resident], ResidentId>,
  'addResponsibleContact' : ActorMethod<
    [ResidentId, string, string, string, string, boolean],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteResident' : ActorMethod<[ResidentId], undefined>,
  'dischargeResident' : ActorMethod<[ResidentId], undefined>,
  'discontinueMedication' : ActorMethod<[ResidentId, bigint], undefined>,
  'getADLRecords' : ActorMethod<[ResidentId], Array<ADLRecord>>,
  'getAllResidents' : ActorMethod<[], Array<Resident>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCodeStatus' : ActorMethod<[ResidentId], [] | [CodeStatus]>,
  'getCodeStatusHistory' : ActorMethod<
    [ResidentId],
    Array<CodeStatusChangeRecord>
  >,
  'getDailyVitals' : ActorMethod<[ResidentId], Array<DailyVitals>>,
  'getHealthStatus' : ActorMethod<[], HealthStatus>,
  'getMARRecords' : ActorMethod<[ResidentId], Array<MARRecord>>,
  'getMedications' : ActorMethod<[ResidentId], Array<Medication>>,
  'getResident' : ActorMethod<[ResidentId], [] | [Resident]>,
  'getResidentStats' : ActorMethod<
    [],
    {
      'activeResidents' : bigint,
      'dischargedResidents' : bigint,
      'totalResidents' : bigint,
    }
  >,
  'getResidentsByFilter' : ActorMethod<
    [[] | [string], [] | [ResidentStatus]],
    Array<Resident>
  >,
  'getResponsibleContacts' : ActorMethod<
    [ResidentId],
    Array<ResponsibleContact>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reactivateMedication' : ActorMethod<[ResidentId, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCodeStatus' : ActorMethod<[ResidentId, CodeStatus, string], undefined>,
  'updateInsuranceInfo' : ActorMethod<[ResidentId, InsuranceInfo], undefined>,
  'updateMedication' : ActorMethod<[ResidentId, bigint, Medication], undefined>,
  'updatePharmacyInfo' : ActorMethod<[ResidentId, PharmacyInfo], undefined>,
  'updatePhysician' : ActorMethod<
    [ResidentId, bigint, string, string, string],
    undefined
  >,
  'updateResident' : ActorMethod<[ResidentId, Resident], undefined>,
  'updateResponsibleContact' : ActorMethod<
    [ResidentId, bigint, string, string, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];