/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResidentId = IDL.Nat;
export const Medication = IDL.Record({
  'id' : IDL.Nat,
  'dosage' : IDL.Text,
  'prescribingPhysicianId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'administrationRoute' : IDL.Text,
  'isActive' : IDL.Bool,
  'administrationTimes' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
  'isPRN' : IDL.Bool,
  'dosageQuantity' : IDL.Text,
});
export const ResidentStatus = IDL.Variant({
  'active' : IDL.Null,
  'discharged' : IDL.Null,
});
export const InsuranceInfo = IDL.Record({
  'groupNumber' : IDL.Text,
  'provider' : IDL.Text,
  'medicaidNumber' : IDL.Opt(IDL.Text),
  'policyNumber' : IDL.Text,
  'medicareNumber' : IDL.Opt(IDL.Text),
});
export const MARRecord = IDL.Record({
  'id' : IDL.Nat,
  'medicationId' : IDL.Nat,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'administrationTime' : IDL.Text,
  'administeredBy' : IDL.Text,
});
export const ADLRecord = IDL.Record({
  'id' : IDL.Nat,
  'staffNotes' : IDL.Text,
  'assistanceLevel' : IDL.Text,
  'date' : IDL.Text,
  'timestamp' : IDL.Int,
  'activity' : IDL.Text,
});
export const PharmacyInfo = IDL.Record({
  'fax' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DailyVitals = IDL.Record({
  'id' : IDL.Nat,
  'temperatureUnit' : IDL.Text,
  'bloodGlucose' : IDL.Opt(IDL.Nat),
  'respiratoryRate' : IDL.Nat,
  'temperature' : IDL.Float64,
  'pulseRate' : IDL.Nat,
  'oxygenSaturation' : IDL.Nat,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'measurementDate' : IDL.Text,
  'bloodPressureDiastolic' : IDL.Nat,
  'measurementTime' : IDL.Text,
  'bloodPressureSystolic' : IDL.Nat,
});
export const ResponsibleContact = IDL.Record({
  'id' : IDL.Nat,
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'isPrimary' : IDL.Bool,
  'phone' : IDL.Text,
});
export const Physician = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
});
export const CodeStatus = IDL.Variant({
  'dnr' : IDL.Null,
  'fullCode' : IDL.Null,
});
export const Resident = IDL.Record({
  'id' : ResidentId,
  'bed' : IDL.Text,
  'dob' : IDL.Text,
  'status' : ResidentStatus,
  'insuranceInfo' : IDL.Opt(InsuranceInfo),
  'admissionDate' : IDL.Text,
  'marRecords' : IDL.Vec(MARRecord),
  'adlRecords' : IDL.Vec(ADLRecord),
  'roomNumber' : IDL.Text,
  'pharmacyInfo' : IDL.Opt(PharmacyInfo),
  'medications' : IDL.Vec(Medication),
  'dailyVitals' : IDL.Vec(DailyVitals),
  'responsibleContacts' : IDL.Vec(ResponsibleContact),
  'medicaidNumber' : IDL.Opt(IDL.Text),
  'physicians' : IDL.Vec(Physician),
  'codeStatus' : CodeStatus,
  'lastName' : IDL.Text,
  'roomType' : IDL.Text,
  'medicareNumber' : IDL.Opt(IDL.Text),
  'firstName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserType = IDL.Variant({
  'familyMember' : IDL.Null,
  'staff' : IDL.Null,
  'resident' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userType' : UserType,
  'name' : IDL.Text,
  'relatedResidentIds' : IDL.Vec(IDL.Nat),
});
export const CodeStatusChangeRecord = IDL.Record({
  'id' : IDL.Nat,
  'residentId' : ResidentId,
  'changedByName' : IDL.Text,
  'changedBy' : IDL.Principal,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'newStatus' : CodeStatus,
  'previousStatus' : CodeStatus,
});
export const HealthStatus = IDL.Variant({
  'ok' : IDL.Text,
  'error' : IDL.Text,
  'maintenance' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addADLRecord' : IDL.Func(
      [ResidentId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addDailyVitals' : IDL.Func(
      [
        ResidentId,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addMARRecord' : IDL.Func(
      [ResidentId, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addMedicationToResident' : IDL.Func([ResidentId, Medication], [IDL.Nat], []),
  'addPhysicianToResident' : IDL.Func(
      [ResidentId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addResident' : IDL.Func([Resident], [ResidentId], []),
  'addResponsibleContact' : IDL.Func(
      [ResidentId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteResident' : IDL.Func([ResidentId], [], []),
  'dischargeResident' : IDL.Func([ResidentId], [], []),
  'discontinueMedication' : IDL.Func([ResidentId, IDL.Nat], [], []),
  'getADLRecords' : IDL.Func([ResidentId], [IDL.Vec(ADLRecord)], ['query']),
  'getAllResidents' : IDL.Func([], [IDL.Vec(Resident)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCodeStatus' : IDL.Func([ResidentId], [IDL.Opt(CodeStatus)], ['query']),
  'getCodeStatusHistory' : IDL.Func(
      [ResidentId],
      [IDL.Vec(CodeStatusChangeRecord)],
      ['query'],
    ),
  'getDailyVitals' : IDL.Func([ResidentId], [IDL.Vec(DailyVitals)], ['query']),
  'getHealthStatus' : IDL.Func([], [HealthStatus], ['query']),
  'getMARRecords' : IDL.Func([ResidentId], [IDL.Vec(MARRecord)], ['query']),
  'getMedications' : IDL.Func([ResidentId], [IDL.Vec(Medication)], ['query']),
  'getResident' : IDL.Func([ResidentId], [IDL.Opt(Resident)], ['query']),
  'getResidentStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeResidents' : IDL.Nat,
          'dischargedResidents' : IDL.Nat,
          'totalResidents' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getResidentsByFilter' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(ResidentStatus)],
      [IDL.Vec(Resident)],
      ['query'],
    ),
  'getResponsibleContacts' : IDL.Func(
      [ResidentId],
      [IDL.Vec(ResponsibleContact)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reactivateMedication' : IDL.Func([ResidentId, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCodeStatus' : IDL.Func([ResidentId, CodeStatus, IDL.Text], [], []),
  'updateInsuranceInfo' : IDL.Func([ResidentId, InsuranceInfo], [], []),
  'updateMedication' : IDL.Func([ResidentId, IDL.Nat, Medication], [], []),
  'updatePharmacyInfo' : IDL.Func([ResidentId, PharmacyInfo], [], []),
  'updatePhysician' : IDL.Func(
      [ResidentId, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateResident' : IDL.Func([ResidentId, Resident], [], []),
  'updateResponsibleContact' : IDL.Func(
      [ResidentId, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResidentId = IDL.Nat;
  const Medication = IDL.Record({
    'id' : IDL.Nat,
    'dosage' : IDL.Text,
    'prescribingPhysicianId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'administrationRoute' : IDL.Text,
    'isActive' : IDL.Bool,
    'administrationTimes' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
    'isPRN' : IDL.Bool,
    'dosageQuantity' : IDL.Text,
  });
  const ResidentStatus = IDL.Variant({
    'active' : IDL.Null,
    'discharged' : IDL.Null,
  });
  const InsuranceInfo = IDL.Record({
    'groupNumber' : IDL.Text,
    'provider' : IDL.Text,
    'medicaidNumber' : IDL.Opt(IDL.Text),
    'policyNumber' : IDL.Text,
    'medicareNumber' : IDL.Opt(IDL.Text),
  });
  const MARRecord = IDL.Record({
    'id' : IDL.Nat,
    'medicationId' : IDL.Nat,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'administrationTime' : IDL.Text,
    'administeredBy' : IDL.Text,
  });
  const ADLRecord = IDL.Record({
    'id' : IDL.Nat,
    'staffNotes' : IDL.Text,
    'assistanceLevel' : IDL.Text,
    'date' : IDL.Text,
    'timestamp' : IDL.Int,
    'activity' : IDL.Text,
  });
  const PharmacyInfo = IDL.Record({
    'fax' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DailyVitals = IDL.Record({
    'id' : IDL.Nat,
    'temperatureUnit' : IDL.Text,
    'bloodGlucose' : IDL.Opt(IDL.Nat),
    'respiratoryRate' : IDL.Nat,
    'temperature' : IDL.Float64,
    'pulseRate' : IDL.Nat,
    'oxygenSaturation' : IDL.Nat,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'measurementDate' : IDL.Text,
    'bloodPressureDiastolic' : IDL.Nat,
    'measurementTime' : IDL.Text,
    'bloodPressureSystolic' : IDL.Nat,
  });
  const ResponsibleContact = IDL.Record({
    'id' : IDL.Nat,
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'isPrimary' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const Physician = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
  });
  const CodeStatus = IDL.Variant({ 'dnr' : IDL.Null, 'fullCode' : IDL.Null });
  const Resident = IDL.Record({
    'id' : ResidentId,
    'bed' : IDL.Text,
    'dob' : IDL.Text,
    'status' : ResidentStatus,
    'insuranceInfo' : IDL.Opt(InsuranceInfo),
    'admissionDate' : IDL.Text,
    'marRecords' : IDL.Vec(MARRecord),
    'adlRecords' : IDL.Vec(ADLRecord),
    'roomNumber' : IDL.Text,
    'pharmacyInfo' : IDL.Opt(PharmacyInfo),
    'medications' : IDL.Vec(Medication),
    'dailyVitals' : IDL.Vec(DailyVitals),
    'responsibleContacts' : IDL.Vec(ResponsibleContact),
    'medicaidNumber' : IDL.Opt(IDL.Text),
    'physicians' : IDL.Vec(Physician),
    'codeStatus' : CodeStatus,
    'lastName' : IDL.Text,
    'roomType' : IDL.Text,
    'medicareNumber' : IDL.Opt(IDL.Text),
    'firstName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserType = IDL.Variant({
    'familyMember' : IDL.Null,
    'staff' : IDL.Null,
    'resident' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userType' : UserType,
    'name' : IDL.Text,
    'relatedResidentIds' : IDL.Vec(IDL.Nat),
  });
  const CodeStatusChangeRecord = IDL.Record({
    'id' : IDL.Nat,
    'residentId' : ResidentId,
    'changedByName' : IDL.Text,
    'changedBy' : IDL.Principal,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'newStatus' : CodeStatus,
    'previousStatus' : CodeStatus,
  });
  const HealthStatus = IDL.Variant({
    'ok' : IDL.Text,
    'error' : IDL.Text,
    'maintenance' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addADLRecord' : IDL.Func(
        [ResidentId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addDailyVitals' : IDL.Func(
        [
          ResidentId,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addMARRecord' : IDL.Func(
        [ResidentId, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addMedicationToResident' : IDL.Func(
        [ResidentId, Medication],
        [IDL.Nat],
        [],
      ),
    'addPhysicianToResident' : IDL.Func(
        [ResidentId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addResident' : IDL.Func([Resident], [ResidentId], []),
    'addResponsibleContact' : IDL.Func(
        [ResidentId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteResident' : IDL.Func([ResidentId], [], []),
    'dischargeResident' : IDL.Func([ResidentId], [], []),
    'discontinueMedication' : IDL.Func([ResidentId, IDL.Nat], [], []),
    'getADLRecords' : IDL.Func([ResidentId], [IDL.Vec(ADLRecord)], ['query']),
    'getAllResidents' : IDL.Func([], [IDL.Vec(Resident)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCodeStatus' : IDL.Func([ResidentId], [IDL.Opt(CodeStatus)], ['query']),
    'getCodeStatusHistory' : IDL.Func(
        [ResidentId],
        [IDL.Vec(CodeStatusChangeRecord)],
        ['query'],
      ),
    'getDailyVitals' : IDL.Func(
        [ResidentId],
        [IDL.Vec(DailyVitals)],
        ['query'],
      ),
    'getHealthStatus' : IDL.Func([], [HealthStatus], ['query']),
    'getMARRecords' : IDL.Func([ResidentId], [IDL.Vec(MARRecord)], ['query']),
    'getMedications' : IDL.Func([ResidentId], [IDL.Vec(Medication)], ['query']),
    'getResident' : IDL.Func([ResidentId], [IDL.Opt(Resident)], ['query']),
    'getResidentStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeResidents' : IDL.Nat,
            'dischargedResidents' : IDL.Nat,
            'totalResidents' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getResidentsByFilter' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(ResidentStatus)],
        [IDL.Vec(Resident)],
        ['query'],
      ),
    'getResponsibleContacts' : IDL.Func(
        [ResidentId],
        [IDL.Vec(ResponsibleContact)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reactivateMedication' : IDL.Func([ResidentId, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCodeStatus' : IDL.Func([ResidentId, CodeStatus, IDL.Text], [], []),
    'updateInsuranceInfo' : IDL.Func([ResidentId, InsuranceInfo], [], []),
    'updateMedication' : IDL.Func([ResidentId, IDL.Nat, Medication], [], []),
    'updatePharmacyInfo' : IDL.Func([ResidentId, PharmacyInfo], [], []),
    'updatePhysician' : IDL.Func(
        [ResidentId, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateResident' : IDL.Func([ResidentId, Resident], [], []),
    'updateResponsibleContact' : IDL.Func(
        [ResidentId, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };