/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    userType: UserType;
    name: string;
    relatedResidentIds: Array<bigint>;
}
export interface PharmacyInfo {
    id: bigint;
    fax: string;
    name: string;
    address: string;
    phone: string;
}
export type MedicationId = bigint;
export interface Resident {
    id: ResidentId;
    bed: string;
    dob: string;
    status: ResidentStatus;
    insuranceInfos: Array<InsuranceInfo>;
    admissionDate: string;
    marRecords: Array<MARRecord>;
    adlRecords: Array<ADLRecord>;
    roomNumber: string;
    medications: Array<Medication>;
    dailyVitals: Array<DailyVitals>;
    responsibleContacts: Array<ResponsibleContact>;
    medicaidNumber?: string;
    physicians: Array<Physician>;
    codeStatus: CodeStatus;
    lastName: string;
    roomType: string;
    medicareNumber?: string;
    pharmacyInfos: Array<PharmacyInfo>;
    firstName: string;
}
export interface Physician {
    id: bigint;
    contactInfo: string;
    name: string;
    specialty: string;
}
export interface MARRecord {
    id: bigint;
    medicationId: MedicationId;
    notes: string;
    timestamp: bigint;
    administrationTime: string;
    administeredBy: string;
}
export type HealthStatus = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "error";
    error: string;
} | {
    __kind__: "maintenance";
    maintenance: string;
};
export interface ADLRecord {
    id: bigint;
    staffNotes: string;
    assistanceLevel: string;
    date: string;
    timestamp: bigint;
    activity: string;
}
export interface CodeStatusChangeRecord {
    id: bigint;
    residentId: ResidentId;
    changedByName: string;
    changedBy: Principal;
    notes: string;
    timestamp: bigint;
    newStatus: CodeStatus;
    previousStatus: CodeStatus;
}
export interface ResponsibleContact {
    id: bigint;
    relationship: string;
    name: string;
    email: string;
    isPrimary: boolean;
    phone: string;
}
export interface DisplayPreferences {
    showPrintProfileButton: boolean;
    residentProfileEditorBackgroundMode: BackgroundMode;
}
export interface AppSettings {
    displayPreferences: DisplayPreferences;
}
export interface DailyVitals {
    id: bigint;
    temperatureUnit: string;
    bloodGlucose?: bigint;
    respiratoryRate: bigint;
    temperature: number;
    pulseRate: bigint;
    oxygenSaturation: bigint;
    notes: string;
    timestamp: bigint;
    measurementDate: string;
    bloodPressureDiastolic: bigint;
    measurementTime: string;
    bloodPressureSystolic: bigint;
}
export type ResidentId = bigint;
export interface Medication {
    id: MedicationId;
    dosage: string;
    prescribingPhysicianId?: bigint;
    name: string;
    administrationRoute: string;
    isActive: boolean;
    administrationTimes: Array<string>;
    notes: string;
    isPRN: boolean;
    dosageQuantity: string;
}
export interface InsuranceInfo {
    id: bigint;
    groupNumber: string;
    provider: string;
    medicaidNumber?: string;
    policyNumber: string;
    medicareNumber?: string;
}
export enum BackgroundMode {
    solidBlack = "solidBlack",
    solidWhite = "solidWhite"
}
export enum CodeStatus {
    dnr = "dnr",
    fullCode = "fullCode"
}
export enum ResidentStatus {
    active = "active",
    discharged = "discharged"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserType {
    familyMember = "familyMember",
    staff = "staff",
    resident = "resident"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addADLRecord(residentId: ResidentId, date: string, activity: string, assistanceLevel: string, staffNotes: string): Promise<bigint>;
    addDailyVitals(residentId: ResidentId, temperature: number, temperatureUnit: string, bloodPressureSystolic: bigint, bloodPressureDiastolic: bigint, pulseRate: bigint, respiratoryRate: bigint, oxygenSaturation: bigint, bloodGlucose: bigint | null, measurementDate: string, measurementTime: string, notes: string): Promise<bigint>;
    addInsuranceInfo(residentId: ResidentId, insurance: InsuranceInfo): Promise<bigint>;
    addMARRecord(residentId: ResidentId, medicationId: MedicationId, administrationTime: string, administeredBy: string, notes: string): Promise<bigint>;
    addMedication(residentId: ResidentId, medication: Medication): Promise<MedicationId>;
    addPharmacyInfo(residentId: ResidentId, pharmacy: PharmacyInfo): Promise<bigint>;
    addPhysician(residentId: ResidentId, physician: Physician): Promise<bigint>;
    addResident(residentData: Resident): Promise<ResidentId>;
    addResponsibleContact(residentId: ResidentId, contact: ResponsibleContact): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteInsuranceInfo(residentId: ResidentId, insuranceId: bigint): Promise<void>;
    deletePharmacyInfo(residentId: ResidentId, pharmacyId: bigint): Promise<void>;
    deletePhysician(residentId: ResidentId, physicianId: bigint): Promise<void>;
    deleteResident(residentId: ResidentId): Promise<void>;
    deleteResponsibleContact(residentId: ResidentId, contactId: bigint): Promise<void>;
    discontinueMedication(residentId: ResidentId, medicationId: MedicationId): Promise<void>;
    getADLRecords(residentId: ResidentId): Promise<Array<ADLRecord>>;
    getAllResidents(): Promise<Array<Resident>>;
    getAppSettings(): Promise<AppSettings>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCodeStatus(residentId: ResidentId): Promise<CodeStatus | null>;
    getCodeStatusHistory(residentId: ResidentId): Promise<Array<CodeStatusChangeRecord>>;
    getHealthStatus(): Promise<HealthStatus>;
    getInsuranceInfo(residentId: ResidentId, insuranceId: bigint): Promise<InsuranceInfo | null>;
    getMARRecords(residentId: ResidentId): Promise<Array<MARRecord>>;
    getMedication(residentId: ResidentId, medicationId: MedicationId): Promise<Medication | null>;
    getPharmacyInfo(residentId: ResidentId, pharmacyId: bigint): Promise<PharmacyInfo | null>;
    getPhysician(residentId: ResidentId, physicianId: bigint): Promise<Physician | null>;
    getResident(residentId: ResidentId): Promise<Resident | null>;
    getResidentStats(): Promise<{
        activeResidents: bigint;
        dischargedResidents: bigint;
        totalResidents: bigint;
    }>;
    getResidentsByFilter(roomNumber: string | null, status: ResidentStatus | null): Promise<Array<Resident>>;
    getResponsibleContact(residentId: ResidentId, contactId: bigint): Promise<ResponsibleContact | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    reactivateMedication(residentId: ResidentId, medicationId: MedicationId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCodeStatus(residentId: ResidentId, newCodeStatus: CodeStatus, notes: string): Promise<void>;
    updateDisplayPreferences(preferences: DisplayPreferences): Promise<void>;
    updateInsuranceInfo(residentId: ResidentId, insuranceId: bigint, updatedInsurance: InsuranceInfo): Promise<void>;
    updateMedication(residentId: ResidentId, medicationId: MedicationId, updatedMedication: Medication): Promise<void>;
    updatePharmacyInfo(residentId: ResidentId, pharmacyId: bigint, updatedPharmacy: PharmacyInfo): Promise<void>;
    updatePhysician(residentId: ResidentId, physicianId: bigint, updatedPhysician: Physician): Promise<void>;
    updateResident(residentId: ResidentId, updatedData: Resident): Promise<void>;
    updateResponsibleContact(residentId: ResidentId, contactId: bigint, updatedContact: ResponsibleContact): Promise<void>;
}
import type { ADLRecord as _ADLRecord, AppSettings as _AppSettings, BackgroundMode as _BackgroundMode, CodeStatus as _CodeStatus, CodeStatusChangeRecord as _CodeStatusChangeRecord, DailyVitals as _DailyVitals, DisplayPreferences as _DisplayPreferences, HealthStatus as _HealthStatus, InsuranceInfo as _InsuranceInfo, MARRecord as _MARRecord, Medication as _Medication, MedicationId as _MedicationId, PharmacyInfo as _PharmacyInfo, Physician as _Physician, Resident as _Resident, ResidentId as _ResidentId, ResidentStatus as _ResidentStatus, ResponsibleContact as _ResponsibleContact, UserProfile as _UserProfile, UserRole as _UserRole, UserType as _UserType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addADLRecord(arg0: ResidentId, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addADLRecord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addADLRecord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addDailyVitals(arg0: ResidentId, arg1: number, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint | null, arg9: string, arg10: string, arg11: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyVitals(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyVitals(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11);
            return result;
        }
    }
    async addInsuranceInfo(arg0: ResidentId, arg1: InsuranceInfo): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInsuranceInfo(arg0, to_candid_InsuranceInfo_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInsuranceInfo(arg0, to_candid_InsuranceInfo_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addMARRecord(arg0: ResidentId, arg1: MedicationId, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMARRecord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMARRecord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addMedication(arg0: ResidentId, arg1: Medication): Promise<MedicationId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedication(arg0, to_candid_Medication_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedication(arg0, to_candid_Medication_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addPharmacyInfo(arg0: ResidentId, arg1: PharmacyInfo): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPharmacyInfo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPharmacyInfo(arg0, arg1);
            return result;
        }
    }
    async addPhysician(arg0: ResidentId, arg1: Physician): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhysician(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhysician(arg0, arg1);
            return result;
        }
    }
    async addResident(arg0: Resident): Promise<ResidentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addResident(to_candid_Resident_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResident(to_candid_Resident_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addResponsibleContact(arg0: ResidentId, arg1: ResponsibleContact): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addResponsibleContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResponsibleContact(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteInsuranceInfo(arg0: ResidentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInsuranceInfo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInsuranceInfo(arg0, arg1);
            return result;
        }
    }
    async deletePharmacyInfo(arg0: ResidentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePharmacyInfo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePharmacyInfo(arg0, arg1);
            return result;
        }
    }
    async deletePhysician(arg0: ResidentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhysician(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhysician(arg0, arg1);
            return result;
        }
    }
    async deleteResident(arg0: ResidentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResident(arg0);
            return result;
        }
    }
    async deleteResponsibleContact(arg0: ResidentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResponsibleContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResponsibleContact(arg0, arg1);
            return result;
        }
    }
    async discontinueMedication(arg0: ResidentId, arg1: MedicationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.discontinueMedication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.discontinueMedication(arg0, arg1);
            return result;
        }
    }
    async getADLRecords(arg0: ResidentId): Promise<Array<ADLRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getADLRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getADLRecords(arg0);
            return result;
        }
    }
    async getAllResidents(): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResidents();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResidents();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppSettings();
                return from_candid_AppSettings_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppSettings();
            return from_candid_AppSettings_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCodeStatus(arg0: ResidentId): Promise<CodeStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCodeStatus(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCodeStatus(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCodeStatusHistory(arg0: ResidentId): Promise<Array<CodeStatusChangeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCodeStatusHistory(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCodeStatusHistory(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthStatus(): Promise<HealthStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthStatus();
                return from_candid_HealthStatus_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthStatus();
            return from_candid_HealthStatus_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInsuranceInfo(arg0: ResidentId, arg1: bigint): Promise<InsuranceInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsuranceInfo(arg0, arg1);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsuranceInfo(arg0, arg1);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMARRecords(arg0: ResidentId): Promise<Array<MARRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMARRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMARRecords(arg0);
            return result;
        }
    }
    async getMedication(arg0: ResidentId, arg1: MedicationId): Promise<Medication | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedication(arg0, arg1);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedication(arg0, arg1);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPharmacyInfo(arg0: ResidentId, arg1: bigint): Promise<PharmacyInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPharmacyInfo(arg0, arg1);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPharmacyInfo(arg0, arg1);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhysician(arg0: ResidentId, arg1: bigint): Promise<Physician | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhysician(arg0, arg1);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhysician(arg0, arg1);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResident(arg0: ResidentId): Promise<Resident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResident(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResident(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResidentStats(): Promise<{
        activeResidents: bigint;
        dischargedResidents: bigint;
        totalResidents: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidentStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidentStats();
            return result;
        }
    }
    async getResidentsByFilter(arg0: string | null, arg1: ResidentStatus | null): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidentsByFilter(to_candid_opt_n61(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidentsByFilter(to_candid_opt_n61(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResponsibleContact(arg0: ResidentId, arg1: bigint): Promise<ResponsibleContact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResponsibleContact(arg0, arg1);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResponsibleContact(arg0, arg1);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reactivateMedication(arg0: ResidentId, arg1: MedicationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateMedication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateMedication(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCodeStatus(arg0: ResidentId, arg1: CodeStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCodeStatus(arg0, to_candid_CodeStatus_n15(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCodeStatus(arg0, to_candid_CodeStatus_n15(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateDisplayPreferences(arg0: DisplayPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayPreferences(to_candid_DisplayPreferences_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayPreferences(to_candid_DisplayPreferences_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInsuranceInfo(arg0: ResidentId, arg1: bigint, arg2: InsuranceInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInsuranceInfo(arg0, arg1, to_candid_InsuranceInfo_n2(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInsuranceInfo(arg0, arg1, to_candid_InsuranceInfo_n2(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateMedication(arg0: ResidentId, arg1: MedicationId, arg2: Medication): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedication(arg0, arg1, to_candid_Medication_n4(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedication(arg0, arg1, to_candid_Medication_n4(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updatePharmacyInfo(arg0: ResidentId, arg1: bigint, arg2: PharmacyInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePharmacyInfo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePharmacyInfo(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePhysician(arg0: ResidentId, arg1: bigint, arg2: Physician): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePhysician(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePhysician(arg0, arg1, arg2);
            return result;
        }
    }
    async updateResident(arg0: ResidentId, arg1: Resident): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResident(arg0, to_candid_Resident_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResident(arg0, to_candid_Resident_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateResponsibleContact(arg0: ResidentId, arg1: bigint, arg2: ResponsibleContact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResponsibleContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResponsibleContact(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AppSettings_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppSettings): AppSettings {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_BackgroundMode_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackgroundMode): BackgroundMode {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_CodeStatusChangeRecord_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CodeStatusChangeRecord): CodeStatusChangeRecord {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_CodeStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CodeStatus): CodeStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_DailyVitals_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyVitals): DailyVitals {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_DisplayPreferences_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisplayPreferences): DisplayPreferences {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_HealthStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthStatus): HealthStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_InsuranceInfo_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsuranceInfo): InsuranceInfo {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Medication_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medication): Medication {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ResidentStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResidentStatus): ResidentStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Resident_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resident): Resident {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserType): UserType {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CodeStatus]): CodeStatus | null {
    return value.length === 0 ? null : from_candid_CodeStatus_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InsuranceInfo]): InsuranceInfo | null {
    return value.length === 0 ? null : from_candid_InsuranceInfo_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Medication]): Medication | null {
    return value.length === 0 ? null : from_candid_Medication_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PharmacyInfo]): PharmacyInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Physician]): Physician | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resident]): Resident | null {
    return value.length === 0 ? null : from_candid_Resident_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResponsibleContact]): ResponsibleContact | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ResidentId;
    bed: string;
    dob: string;
    status: _ResidentStatus;
    insuranceInfos: Array<_InsuranceInfo>;
    admissionDate: string;
    marRecords: Array<_MARRecord>;
    adlRecords: Array<_ADLRecord>;
    roomNumber: string;
    medications: Array<_Medication>;
    dailyVitals: Array<_DailyVitals>;
    responsibleContacts: Array<_ResponsibleContact>;
    medicaidNumber: [] | [string];
    physicians: Array<_Physician>;
    codeStatus: _CodeStatus;
    lastName: string;
    roomType: string;
    medicareNumber: [] | [string];
    pharmacyInfos: Array<_PharmacyInfo>;
    firstName: string;
}): {
    id: ResidentId;
    bed: string;
    dob: string;
    status: ResidentStatus;
    insuranceInfos: Array<InsuranceInfo>;
    admissionDate: string;
    marRecords: Array<MARRecord>;
    adlRecords: Array<ADLRecord>;
    roomNumber: string;
    medications: Array<Medication>;
    dailyVitals: Array<DailyVitals>;
    responsibleContacts: Array<ResponsibleContact>;
    medicaidNumber?: string;
    physicians: Array<Physician>;
    codeStatus: CodeStatus;
    lastName: string;
    roomType: string;
    medicareNumber?: string;
    pharmacyInfos: Array<PharmacyInfo>;
    firstName: string;
} {
    return {
        id: value.id,
        bed: value.bed,
        dob: value.dob,
        status: from_candid_ResidentStatus_n22(_uploadFile, _downloadFile, value.status),
        insuranceInfos: from_candid_vec_n24(_uploadFile, _downloadFile, value.insuranceInfos),
        admissionDate: value.admissionDate,
        marRecords: value.marRecords,
        adlRecords: value.adlRecords,
        roomNumber: value.roomNumber,
        medications: from_candid_vec_n28(_uploadFile, _downloadFile, value.medications),
        dailyVitals: from_candid_vec_n32(_uploadFile, _downloadFile, value.dailyVitals),
        responsibleContacts: value.responsibleContacts,
        medicaidNumber: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.medicaidNumber)),
        physicians: value.physicians,
        codeStatus: from_candid_CodeStatus_n35(_uploadFile, _downloadFile, value.codeStatus),
        lastName: value.lastName,
        roomType: value.roomType,
        medicareNumber: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.medicareNumber)),
        pharmacyInfos: value.pharmacyInfos,
        firstName: value.firstName
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    groupNumber: string;
    provider: string;
    medicaidNumber: [] | [string];
    policyNumber: string;
    medicareNumber: [] | [string];
}): {
    id: bigint;
    groupNumber: string;
    provider: string;
    medicaidNumber?: string;
    policyNumber: string;
    medicareNumber?: string;
} {
    return {
        id: value.id,
        groupNumber: value.groupNumber,
        provider: value.provider,
        medicaidNumber: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.medicaidNumber)),
        policyNumber: value.policyNumber,
        medicareNumber: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.medicareNumber))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MedicationId;
    dosage: string;
    prescribingPhysicianId: [] | [bigint];
    name: string;
    administrationRoute: string;
    isActive: boolean;
    administrationTimes: Array<string>;
    notes: string;
    isPRN: boolean;
    dosageQuantity: string;
}): {
    id: MedicationId;
    dosage: string;
    prescribingPhysicianId?: bigint;
    name: string;
    administrationRoute: string;
    isActive: boolean;
    administrationTimes: Array<string>;
    notes: string;
    isPRN: boolean;
    dosageQuantity: string;
} {
    return {
        id: value.id,
        dosage: value.dosage,
        prescribingPhysicianId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.prescribingPhysicianId)),
        name: value.name,
        administrationRoute: value.administrationRoute,
        isActive: value.isActive,
        administrationTimes: value.administrationTimes,
        notes: value.notes,
        isPRN: value.isPRN,
        dosageQuantity: value.dosageQuantity
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    temperatureUnit: string;
    bloodGlucose: [] | [bigint];
    respiratoryRate: bigint;
    temperature: number;
    pulseRate: bigint;
    oxygenSaturation: bigint;
    notes: string;
    timestamp: bigint;
    measurementDate: string;
    bloodPressureDiastolic: bigint;
    measurementTime: string;
    bloodPressureSystolic: bigint;
}): {
    id: bigint;
    temperatureUnit: string;
    bloodGlucose?: bigint;
    respiratoryRate: bigint;
    temperature: number;
    pulseRate: bigint;
    oxygenSaturation: bigint;
    notes: string;
    timestamp: bigint;
    measurementDate: string;
    bloodPressureDiastolic: bigint;
    measurementTime: string;
    bloodPressureSystolic: bigint;
} {
    return {
        id: value.id,
        temperatureUnit: value.temperatureUnit,
        bloodGlucose: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.bloodGlucose)),
        respiratoryRate: value.respiratoryRate,
        temperature: value.temperature,
        pulseRate: value.pulseRate,
        oxygenSaturation: value.oxygenSaturation,
        notes: value.notes,
        timestamp: value.timestamp,
        measurementDate: value.measurementDate,
        bloodPressureDiastolic: value.bloodPressureDiastolic,
        measurementTime: value.measurementTime,
        bloodPressureSystolic: value.bloodPressureSystolic
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayPreferences: _DisplayPreferences;
}): {
    displayPreferences: DisplayPreferences;
} {
    return {
        displayPreferences: from_candid_DisplayPreferences_n39(_uploadFile, _downloadFile, value.displayPreferences)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    showPrintProfileButton: boolean;
    residentProfileEditorBackgroundMode: _BackgroundMode;
}): {
    showPrintProfileButton: boolean;
    residentProfileEditorBackgroundMode: BackgroundMode;
} {
    return {
        showPrintProfileButton: value.showPrintProfileButton,
        residentProfileEditorBackgroundMode: from_candid_BackgroundMode_n41(_uploadFile, _downloadFile, value.residentProfileEditorBackgroundMode)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: _UserType;
    name: string;
    relatedResidentIds: Array<bigint>;
}): {
    userType: UserType;
    name: string;
    relatedResidentIds: Array<bigint>;
} {
    return {
        userType: from_candid_UserType_n46(_uploadFile, _downloadFile, value.userType),
        name: value.name,
        relatedResidentIds: value.relatedResidentIds
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    residentId: _ResidentId;
    changedByName: string;
    changedBy: Principal;
    notes: string;
    timestamp: bigint;
    newStatus: _CodeStatus;
    previousStatus: _CodeStatus;
}): {
    id: bigint;
    residentId: ResidentId;
    changedByName: string;
    changedBy: Principal;
    notes: string;
    timestamp: bigint;
    newStatus: CodeStatus;
    previousStatus: CodeStatus;
} {
    return {
        id: value.id,
        residentId: value.residentId,
        changedByName: value.changedByName,
        changedBy: value.changedBy,
        notes: value.notes,
        timestamp: value.timestamp,
        newStatus: from_candid_CodeStatus_n35(_uploadFile, _downloadFile, value.newStatus),
        previousStatus: from_candid_CodeStatus_n35(_uploadFile, _downloadFile, value.previousStatus)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    discharged: null;
}): ResidentStatus {
    return "active" in value ? ResidentStatus.active : "discharged" in value ? ResidentStatus.discharged : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dnr: null;
} | {
    fullCode: null;
}): CodeStatus {
    return "dnr" in value ? CodeStatus.dnr : "fullCode" in value ? CodeStatus.fullCode : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    solidBlack: null;
} | {
    solidWhite: null;
}): BackgroundMode {
    return "solidBlack" in value ? BackgroundMode.solidBlack : "solidWhite" in value ? BackgroundMode.solidWhite : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    familyMember: null;
} | {
    staff: null;
} | {
    resident: null;
}): UserType {
    return "familyMember" in value ? UserType.familyMember : "staff" in value ? UserType.staff : "resident" in value ? UserType.resident : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    error: string;
} | {
    maintenance: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "error";
    error: string;
} | {
    __kind__: "maintenance";
    maintenance: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "maintenance" in value ? {
        __kind__: "maintenance",
        maintenance: value.maintenance
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resident>): Array<Resident> {
    return value.map((x)=>from_candid_Resident_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InsuranceInfo>): Array<InsuranceInfo> {
    return value.map((x)=>from_candid_InsuranceInfo_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medication>): Array<Medication> {
    return value.map((x)=>from_candid_Medication_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyVitals>): Array<DailyVitals> {
    return value.map((x)=>from_candid_DailyVitals_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CodeStatusChangeRecord>): Array<CodeStatusChangeRecord> {
    return value.map((x)=>from_candid_CodeStatusChangeRecord_n52(_uploadFile, _downloadFile, x));
}
function to_candid_BackgroundMode_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundMode): _BackgroundMode {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_CodeStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CodeStatus): _CodeStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_DailyVitals_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyVitals): _DailyVitals {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_DisplayPreferences_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisplayPreferences): _DisplayPreferences {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_InsuranceInfo_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsuranceInfo): _InsuranceInfo {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_Medication_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Medication): _Medication {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ResidentStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResidentStatus): _ResidentStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Resident_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Resident): _Resident {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserType_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): _UserType {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResidentStatus | null): [] | [_ResidentStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ResidentStatus_n8(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    temperatureUnit: string;
    bloodGlucose?: bigint;
    respiratoryRate: bigint;
    temperature: number;
    pulseRate: bigint;
    oxygenSaturation: bigint;
    notes: string;
    timestamp: bigint;
    measurementDate: string;
    bloodPressureDiastolic: bigint;
    measurementTime: string;
    bloodPressureSystolic: bigint;
}): {
    id: bigint;
    temperatureUnit: string;
    bloodGlucose: [] | [bigint];
    respiratoryRate: bigint;
    temperature: number;
    pulseRate: bigint;
    oxygenSaturation: bigint;
    notes: string;
    timestamp: bigint;
    measurementDate: string;
    bloodPressureDiastolic: bigint;
    measurementTime: string;
    bloodPressureSystolic: bigint;
} {
    return {
        id: value.id,
        temperatureUnit: value.temperatureUnit,
        bloodGlucose: value.bloodGlucose ? candid_some(value.bloodGlucose) : candid_none(),
        respiratoryRate: value.respiratoryRate,
        temperature: value.temperature,
        pulseRate: value.pulseRate,
        oxygenSaturation: value.oxygenSaturation,
        notes: value.notes,
        timestamp: value.timestamp,
        measurementDate: value.measurementDate,
        bloodPressureDiastolic: value.bloodPressureDiastolic,
        measurementTime: value.measurementTime,
        bloodPressureSystolic: value.bloodPressureSystolic
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    groupNumber: string;
    provider: string;
    medicaidNumber?: string;
    policyNumber: string;
    medicareNumber?: string;
}): {
    id: bigint;
    groupNumber: string;
    provider: string;
    medicaidNumber: [] | [string];
    policyNumber: string;
    medicareNumber: [] | [string];
} {
    return {
        id: value.id,
        groupNumber: value.groupNumber,
        provider: value.provider,
        medicaidNumber: value.medicaidNumber ? candid_some(value.medicaidNumber) : candid_none(),
        policyNumber: value.policyNumber,
        medicareNumber: value.medicareNumber ? candid_some(value.medicareNumber) : candid_none()
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: MedicationId;
    dosage: string;
    prescribingPhysicianId?: bigint;
    name: string;
    administrationRoute: string;
    isActive: boolean;
    administrationTimes: Array<string>;
    notes: string;
    isPRN: boolean;
    dosageQuantity: string;
}): {
    id: _MedicationId;
    dosage: string;
    prescribingPhysicianId: [] | [bigint];
    name: string;
    administrationRoute: string;
    isActive: boolean;
    administrationTimes: Array<string>;
    notes: string;
    isPRN: boolean;
    dosageQuantity: string;
} {
    return {
        id: value.id,
        dosage: value.dosage,
        prescribingPhysicianId: value.prescribingPhysicianId ? candid_some(value.prescribingPhysicianId) : candid_none(),
        name: value.name,
        administrationRoute: value.administrationRoute,
        isActive: value.isActive,
        administrationTimes: value.administrationTimes,
        notes: value.notes,
        isPRN: value.isPRN,
        dosageQuantity: value.dosageQuantity
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: UserType;
    name: string;
    relatedResidentIds: Array<bigint>;
}): {
    userType: _UserType;
    name: string;
    relatedResidentIds: Array<bigint>;
} {
    return {
        userType: to_candid_UserType_n66(_uploadFile, _downloadFile, value.userType),
        name: value.name,
        relatedResidentIds: value.relatedResidentIds
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    showPrintProfileButton: boolean;
    residentProfileEditorBackgroundMode: BackgroundMode;
}): {
    showPrintProfileButton: boolean;
    residentProfileEditorBackgroundMode: _BackgroundMode;
} {
    return {
        showPrintProfileButton: value.showPrintProfileButton,
        residentProfileEditorBackgroundMode: to_candid_BackgroundMode_n70(_uploadFile, _downloadFile, value.residentProfileEditorBackgroundMode)
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ResidentId;
    bed: string;
    dob: string;
    status: ResidentStatus;
    insuranceInfos: Array<InsuranceInfo>;
    admissionDate: string;
    marRecords: Array<MARRecord>;
    adlRecords: Array<ADLRecord>;
    roomNumber: string;
    medications: Array<Medication>;
    dailyVitals: Array<DailyVitals>;
    responsibleContacts: Array<ResponsibleContact>;
    medicaidNumber?: string;
    physicians: Array<Physician>;
    codeStatus: CodeStatus;
    lastName: string;
    roomType: string;
    medicareNumber?: string;
    pharmacyInfos: Array<PharmacyInfo>;
    firstName: string;
}): {
    id: _ResidentId;
    bed: string;
    dob: string;
    status: _ResidentStatus;
    insuranceInfos: Array<_InsuranceInfo>;
    admissionDate: string;
    marRecords: Array<_MARRecord>;
    adlRecords: Array<_ADLRecord>;
    roomNumber: string;
    medications: Array<_Medication>;
    dailyVitals: Array<_DailyVitals>;
    responsibleContacts: Array<_ResponsibleContact>;
    medicaidNumber: [] | [string];
    physicians: Array<_Physician>;
    codeStatus: _CodeStatus;
    lastName: string;
    roomType: string;
    medicareNumber: [] | [string];
    pharmacyInfos: Array<_PharmacyInfo>;
    firstName: string;
} {
    return {
        id: value.id,
        bed: value.bed,
        dob: value.dob,
        status: to_candid_ResidentStatus_n8(_uploadFile, _downloadFile, value.status),
        insuranceInfos: to_candid_vec_n10(_uploadFile, _downloadFile, value.insuranceInfos),
        admissionDate: value.admissionDate,
        marRecords: value.marRecords,
        adlRecords: value.adlRecords,
        roomNumber: value.roomNumber,
        medications: to_candid_vec_n11(_uploadFile, _downloadFile, value.medications),
        dailyVitals: to_candid_vec_n12(_uploadFile, _downloadFile, value.dailyVitals),
        responsibleContacts: value.responsibleContacts,
        medicaidNumber: value.medicaidNumber ? candid_some(value.medicaidNumber) : candid_none(),
        physicians: value.physicians,
        codeStatus: to_candid_CodeStatus_n15(_uploadFile, _downloadFile, value.codeStatus),
        lastName: value.lastName,
        roomType: value.roomType,
        medicareNumber: value.medicareNumber ? candid_some(value.medicareNumber) : candid_none(),
        pharmacyInfos: value.pharmacyInfos,
        firstName: value.firstName
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CodeStatus): {
    dnr: null;
} | {
    fullCode: null;
} {
    return value == CodeStatus.dnr ? {
        dnr: null
    } : value == CodeStatus.fullCode ? {
        fullCode: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): {
    familyMember: null;
} | {
    staff: null;
} | {
    resident: null;
} {
    return value == UserType.familyMember ? {
        familyMember: null
    } : value == UserType.staff ? {
        staff: null
    } : value == UserType.resident ? {
        resident: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundMode): {
    solidBlack: null;
} | {
    solidWhite: null;
} {
    return value == BackgroundMode.solidBlack ? {
        solidBlack: null
    } : value == BackgroundMode.solidWhite ? {
        solidWhite: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResidentStatus): {
    active: null;
} | {
    discharged: null;
} {
    return value == ResidentStatus.active ? {
        active: null
    } : value == ResidentStatus.discharged ? {
        discharged: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InsuranceInfo>): Array<_InsuranceInfo> {
    return value.map((x)=>to_candid_InsuranceInfo_n2(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Medication>): Array<_Medication> {
    return value.map((x)=>to_candid_Medication_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DailyVitals>): Array<_DailyVitals> {
    return value.map((x)=>to_candid_DailyVitals_n13(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
